<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Homework 5</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-52a95e23b7bbe465f12a407b63e8a523.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="fullcontent">

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Homework 5</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="summarizing-student-data" class="level1">
<h1>Summarizing Student Data</h1>
<p>We begin by loading the tidyverse as we will use it throughout this assignment.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.2
✔ ggplot2   4.0.0     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
</div>
<section id="task-1-read-in-the-data-and-modify" class="level2">
<h2 class="anchored" data-anchor-id="task-1-read-in-the-data-and-modify">Task 1: Read in the Data and Modify</h2>
<p>We start Task 1 by reading in the data in two different ways.</p>
<p>First, we modify the code provided with the download to read in the data from a local file source and combine the two data frames. We use local paths.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>d1<span class="ot">=</span><span class="fu">read.table</span>(<span class="st">"student-mat.csv"</span>,<span class="at">sep=</span><span class="st">";"</span>,<span class="at">header=</span><span class="cn">TRUE</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>d2<span class="ot">=</span><span class="fu">read.table</span>(<span class="st">"student-por.csv"</span>,<span class="at">sep=</span><span class="st">";"</span>,<span class="at">header=</span><span class="cn">TRUE</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>d3<span class="ot">=</span><span class="fu">merge</span>(d1,d2,<span class="at">by=</span><span class="fu">c</span>(<span class="st">"school"</span>,<span class="st">"sex"</span>,<span class="st">"age"</span>,<span class="st">"address"</span>,<span class="st">"famsize"</span>,<span class="st">"Pstatus"</span>,<span class="st">"Medu"</span>,<span class="st">"Fedu"</span>,<span class="st">"Mjob"</span>,<span class="st">"Fjob"</span>,<span class="st">"reason"</span>,<span class="st">"nursery"</span>,<span class="st">"internet"</span>))</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(d3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  school sex age address famsize Pstatus Medu Fedu     Mjob     Fjob     reason
1     GP   F  15       R     GT3       T    1    1  at_home    other       home
2     GP   F  15       R     GT3       T    1    1    other    other reputation
3     GP   F  15       R     GT3       T    2    2  at_home    other reputation
4     GP   F  15       R     GT3       T    2    4 services   health     course
5     GP   F  15       R     GT3       T    3    3 services services reputation
6     GP   F  15       R     GT3       T    3    4 services   health     course
  nursery internet guardian.x traveltime.x studytime.x failures.x schoolsup.x
1     yes      yes     mother            2           4          1         yes
2      no      yes     mother            1           2          2         yes
3     yes       no     mother            1           1          0         yes
4     yes      yes     mother            1           3          0         yes
5     yes      yes      other            2           3          2          no
6     yes      yes     mother            1           3          0         yes
  famsup.x paid.x activities.x higher.x romantic.x famrel.x freetime.x goout.x
1      yes    yes          yes      yes         no        3          1       2
2      yes     no           no      yes        yes        3          3       4
3      yes    yes          yes      yes         no        4          3       1
4      yes    yes          yes      yes         no        4          3       2
5      yes    yes          yes      yes        yes        4          2       1
6      yes    yes          yes      yes         no        4          3       2
  Dalc.x Walc.x health.x absences.x G1.x G2.x G3.x guardian.y traveltime.y
1      1      1        1          2    7   10   10     mother            2
2      2      4        5          2    8    6    5     mother            1
3      1      1        2          8   14   13   13     mother            1
4      1      1        5          2   10    9    8     mother            1
5      2      3        3          8   10   10   10      other            2
6      1      1        5          2   12   12   11     mother            1
  studytime.y failures.y schoolsup.y famsup.y paid.y activities.y higher.y
1           4          0         yes      yes    yes          yes      yes
2           2          0         yes      yes     no           no      yes
3           1          0         yes      yes     no          yes      yes
4           3          0         yes      yes     no          yes      yes
5           3          0          no      yes    yes          yes      yes
6           3          0         yes      yes     no          yes      yes
  romantic.y famrel.y freetime.y goout.y Dalc.y Walc.y health.y absences.y G1.y
1         no        3          1       2      1      1        1          4   13
2        yes        3          3       4      2      4        5          2   13
3         no        4          3       1      1      1        2          8   14
4         no        4          3       2      1      1        5          2   10
5        yes        4          2       1      2      3        3          2   13
6         no        4          3       2      1      1        5          2   11
  G2.y G3.y
1   13   13
2   11   11
3   13   12
4   11   10
5   13   13
6   12   12</code></pre>
</div>
</div>
<p>Second, we read in the data sets separately and then combine them using functions from the tidyverse. We use <code>inner_join()</code> on the variables used in the code from the website</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>data_mat <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(<span class="st">'student-mat.csv'</span>, <span class="at">delim =</span> <span class="st">';'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 395 Columns: 33
── Column specification ────────────────────────────────────────────────────────
Delimiter: ";"
chr (17): school, sex, address, famsize, Pstatus, Mjob, Fjob, reason, guardi...
dbl (16): age, Medu, Fedu, traveltime, studytime, failures, famrel, freetime...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>data_por <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(<span class="st">'student-por.csv'</span>, <span class="at">delim =</span> <span class="st">';'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 649 Columns: 33
── Column specification ────────────────────────────────────────────────────────
Delimiter: ";"
chr (17): school, sex, address, famsize, Pstatus, Mjob, Fjob, reason, guardi...
dbl (16): age, Medu, Fedu, traveltime, studytime, failures, famrel, freetime...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>data_join1 <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(data_mat, data_por, <span class="at">by=</span><span class="fu">c</span>(<span class="st">"school"</span>,<span class="st">"sex"</span>,<span class="st">"age"</span>,<span class="st">"address"</span>,<span class="st">"famsize"</span>,<span class="st">"Pstatus"</span>,<span class="st">"Medu"</span>,<span class="st">"Fedu"</span>,<span class="st">"Mjob"</span>,<span class="st">"Fjob"</span>,<span class="st">"reason"</span>,<span class="st">"nursery"</span>,<span class="st">"internet"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in inner_join(data_mat, data_por, by = c("school", "sex", "age", : Detected an unexpected many-to-many relationship between `x` and `y`.
ℹ Row 79 of `x` matches multiple rows in `y`.
ℹ Row 79 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship =
  "many-to-many"` to silence this warning.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>data_join1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 382 × 53
   school sex     age address famsize Pstatus  Medu  Fedu Mjob     Fjob   reason
   &lt;chr&gt;  &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;  &lt;chr&gt; 
 1 GP     F        18 U       GT3     A           4     4 at_home  teach… course
 2 GP     F        17 U       GT3     T           1     1 at_home  other  course
 3 GP     F        15 U       LE3     T           1     1 at_home  other  other 
 4 GP     F        15 U       GT3     T           4     2 health   servi… home  
 5 GP     F        16 U       GT3     T           3     3 other    other  home  
 6 GP     M        16 U       LE3     T           4     3 services other  reput…
 7 GP     M        16 U       LE3     T           2     2 other    other  home  
 8 GP     F        17 U       GT3     A           4     4 other    teach… home  
 9 GP     M        15 U       LE3     A           3     2 services other  home  
10 GP     M        15 U       GT3     T           3     4 other    other  home  
# ℹ 372 more rows
# ℹ 42 more variables: guardian.x &lt;chr&gt;, traveltime.x &lt;dbl&gt;, studytime.x &lt;dbl&gt;,
#   failures.x &lt;dbl&gt;, schoolsup.x &lt;chr&gt;, famsup.x &lt;chr&gt;, paid.x &lt;chr&gt;,
#   activities.x &lt;chr&gt;, nursery &lt;chr&gt;, higher.x &lt;chr&gt;, internet &lt;chr&gt;,
#   romantic.x &lt;chr&gt;, famrel.x &lt;dbl&gt;, freetime.x &lt;dbl&gt;, goout.x &lt;dbl&gt;,
#   Dalc.x &lt;dbl&gt;, Walc.x &lt;dbl&gt;, health.x &lt;dbl&gt;, absences.x &lt;dbl&gt;, G1.x &lt;dbl&gt;,
#   G2.x &lt;dbl&gt;, G3.x &lt;dbl&gt;, guardian.y &lt;chr&gt;, traveltime.y &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>The problem we see is that row 79 of <code>data_mat</code> matches multiple rows of <code>data-por</code>. This means rows won’t be joined in a one-to-one fashion.</p>
<p>Now we do an inner join on the math and portuguese data by all variables except <code>G1</code>, <code>G2</code>, <code>G3</code>, <code>paid</code>, and <code>absences</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>data_join2 <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(data_mat, data_por, <span class="at">by =</span> <span class="fu">names</span>(data_mat)[<span class="sc">!</span>(<span class="fu">names</span>(data_mat) <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">'G1'</span>, <span class="st">'G2'</span>, <span class="st">'G3'</span>, <span class="st">'paid'</span>, <span class="st">'absences'</span>))])</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>data_join2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 320 × 38
   school sex     age address famsize Pstatus  Medu  Fedu Mjob     Fjob   reason
   &lt;chr&gt;  &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;  &lt;chr&gt; 
 1 GP     F        18 U       GT3     A           4     4 at_home  teach… course
 2 GP     F        17 U       GT3     T           1     1 at_home  other  course
 3 GP     F        15 U       GT3     T           4     2 health   servi… home  
 4 GP     F        16 U       GT3     T           3     3 other    other  home  
 5 GP     M        16 U       LE3     T           4     3 services other  reput…
 6 GP     M        16 U       LE3     T           2     2 other    other  home  
 7 GP     F        17 U       GT3     A           4     4 other    teach… home  
 8 GP     M        15 U       LE3     A           3     2 services other  home  
 9 GP     M        15 U       GT3     T           3     4 other    other  home  
10 GP     F        15 U       GT3     T           4     4 teacher  health reput…
# ℹ 310 more rows
# ℹ 27 more variables: guardian &lt;chr&gt;, traveltime &lt;dbl&gt;, studytime &lt;dbl&gt;,
#   failures &lt;dbl&gt;, schoolsup &lt;chr&gt;, famsup &lt;chr&gt;, paid.x &lt;chr&gt;,
#   activities &lt;chr&gt;, nursery &lt;chr&gt;, higher &lt;chr&gt;, internet &lt;chr&gt;,
#   romantic &lt;chr&gt;, famrel &lt;dbl&gt;, freetime &lt;dbl&gt;, goout &lt;dbl&gt;, Dalc &lt;dbl&gt;,
#   Walc &lt;dbl&gt;, health &lt;dbl&gt;, absences.x &lt;dbl&gt;, G1.x &lt;dbl&gt;, G2.x &lt;dbl&gt;,
#   G3.x &lt;dbl&gt;, paid.y &lt;chr&gt;, absences.y &lt;dbl&gt;, G1.y &lt;dbl&gt;, G2.y &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>As expected, there are 38 variables. 28 are the matched columns which we specified in the join. The remaining 10 variables comprise the 5 pairs of G1, G2, G3, paid, and absences variables, where one member of a pair is from the math data (those ending in .x) and the other member of the pair is from the portuguese data (those ending in .y).</p>
<p>To complete this task, we choose 4 categorical variables we are interested in and convert these to factors in each of <code>data_mat</code>, <code>data_por</code>, and <code>data_join2</code> tibbles. We will chose <code>school</code>, <code>sex</code>, <code>Medu</code>, and <code>Mjob</code> as our categorical variables. We also choose names for some of the levels that are more interpretable than the default names.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>data_mat <span class="ot">&lt;-</span> data_mat <span class="sc">|&gt;</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">school =</span> <span class="fu">as.factor</span>(school),</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">sex =</span> <span class="fu">factor</span>(sex, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">'F'</span>, <span class="st">'M'</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">'Female'</span>, <span class="st">'Male'</span>)),</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">Medu =</span> <span class="fu">factor</span>(Medu, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">0</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">'Higher_Ed'</span>, <span class="st">'Secondary'</span>, <span class="st">'5th_to_9th'</span>, <span class="st">'Primary'</span>, <span class="st">'None'</span>)),</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">Mjob =</span> <span class="fu">as.factor</span>(Mjob))</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>data_por <span class="ot">&lt;-</span> data_por <span class="sc">|&gt;</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">school =</span> <span class="fu">as.factor</span>(school),</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">sex =</span> <span class="fu">factor</span>(sex, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">'F'</span>, <span class="st">'M'</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">'Female'</span>, <span class="st">'Male'</span>)),</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">Medu =</span> <span class="fu">factor</span>(Medu, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">0</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">'Higher_Ed'</span>, <span class="st">'Secondary'</span>, <span class="st">'5th_to_9th'</span>, <span class="st">'Primary'</span>, <span class="st">'None'</span>)),</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">Mjob =</span> <span class="fu">as.factor</span>(Mjob))</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>data_join2 <span class="ot">&lt;-</span> data_join2 <span class="sc">|&gt;</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">school =</span> <span class="fu">as.factor</span>(school),</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>         <span class="at">sex =</span> <span class="fu">factor</span>(sex, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">'F'</span>, <span class="st">'M'</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">'Female'</span>, <span class="st">'Male'</span>)),</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>         <span class="at">Medu =</span> <span class="fu">factor</span>(Medu, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">0</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">'Higher_Ed'</span>, <span class="st">'Secondary'</span>, <span class="st">'5th_to_9th'</span>, <span class="st">'Primary'</span>, <span class="st">'None'</span>)),</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>         <span class="at">Mjob =</span> <span class="fu">as.factor</span>(Mjob))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="task-2-summarize-the-data-very-basic-eda" class="level2">
<h2 class="anchored" data-anchor-id="task-2-summarize-the-data-very-basic-eda">Task 2: Summarize the Data (Very Basic EDA)</h2>
<p>On the combined data set (<code>data_join2</code>) we look at how the data is stored and document any missing values.</p>
<p>First, to look at how the data is stored, we call the tibble.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>data_join2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 320 × 38
   school sex      age address famsize Pstatus Medu      Fedu Mjob  Fjob  reason
   &lt;fct&gt;  &lt;fct&gt;  &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;fct&gt;    &lt;dbl&gt; &lt;fct&gt; &lt;chr&gt; &lt;chr&gt; 
 1 GP     Female    18 U       GT3     A       Higher_…     4 at_h… teac… course
 2 GP     Female    17 U       GT3     T       Primary      1 at_h… other course
 3 GP     Female    15 U       GT3     T       Higher_…     2 heal… serv… home  
 4 GP     Female    16 U       GT3     T       Seconda…     3 other other home  
 5 GP     Male      16 U       LE3     T       Higher_…     3 serv… other reput…
 6 GP     Male      16 U       LE3     T       5th_to_…     2 other other home  
 7 GP     Female    17 U       GT3     A       Higher_…     4 other teac… home  
 8 GP     Male      15 U       LE3     A       Seconda…     2 serv… other home  
 9 GP     Male      15 U       GT3     T       Seconda…     4 other other home  
10 GP     Female    15 U       GT3     T       Higher_…     4 teac… heal… reput…
# ℹ 310 more rows
# ℹ 27 more variables: guardian &lt;chr&gt;, traveltime &lt;dbl&gt;, studytime &lt;dbl&gt;,
#   failures &lt;dbl&gt;, schoolsup &lt;chr&gt;, famsup &lt;chr&gt;, paid.x &lt;chr&gt;,
#   activities &lt;chr&gt;, nursery &lt;chr&gt;, higher &lt;chr&gt;, internet &lt;chr&gt;,
#   romantic &lt;chr&gt;, famrel &lt;dbl&gt;, freetime &lt;dbl&gt;, goout &lt;dbl&gt;, Dalc &lt;dbl&gt;,
#   Walc &lt;dbl&gt;, health &lt;dbl&gt;, absences.x &lt;dbl&gt;, G1.x &lt;dbl&gt;, G2.x &lt;dbl&gt;,
#   G3.x &lt;dbl&gt;, paid.y &lt;chr&gt;, absences.y &lt;dbl&gt;, G1.y &lt;dbl&gt;, G2.y &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>We see our 4 chosen categorical variables from Task 1 are now stored as factors. Several variables are stored as doubles where they would be better represented as characters or factors. An example is <code>Fedu</code>, the father’s level of education. Since this variable takes on one of a small set of possible values, it is better represented as a categorical variable, rather than as a numeric variable as it is stored. Other variables that would be better represented as factors or characters but are stored as doubles include <code>traveltime</code>, <code>studytime</code>, and <code>failures</code>. <code>famrel</code>, <code>freetime</code>, <code>goout</code>, <code>Dalc</code>, <code>Walc</code>, and <code>health</code> are all stored as doubles. These variables take values on a Likert-type scale, which we learned in ST 517 can be treated as numeric or categorical, but the preference in that course was to treat them as categorical. Therefore, these may be better served by being stored as characters or factors. All of the above changes in data types in the tibble could be made with the methods of Task 1. We will not do this here since we are not using these variables in this assignment. Finally, we see the G1, G2, G3, absences, and paid variables (for both .x and .y) are appropriately stored as doubles.</p>
<p>Second, we can check for missing values using base R or tidyverse. First for base R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(data_join2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    school        sex        age    address    famsize    Pstatus       Medu 
         0          0          0          0          0          0          0 
      Fedu       Mjob       Fjob     reason   guardian traveltime  studytime 
         0          0          0          0          0          0          0 
  failures  schoolsup     famsup     paid.x activities    nursery     higher 
         0          0          0          0          0          0          0 
  internet   romantic     famrel   freetime      goout       Dalc       Walc 
         0          0          0          0          0          0          0 
    health absences.x       G1.x       G2.x       G3.x     paid.y absences.y 
         0          0          0          0          0          0          0 
      G1.y       G2.y       G3.y 
         0          0          0 </code></pre>
</div>
</div>
<p>We see from the output that there are no missing values.</p>
<p>We could check the same using the tidyverse.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>sum_na <span class="ot">&lt;-</span> <span class="cf">function</span>(v){</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">is.na</span>(v))</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>data_join2 <span class="sc">|&gt;</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), sum_na)) <span class="sc">|&gt;</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width =</span> <span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 38
  school   sex   age address famsize Pstatus  Medu  Fedu  Mjob  Fjob reason
   &lt;int&gt; &lt;int&gt; &lt;int&gt;   &lt;int&gt;   &lt;int&gt;   &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;  &lt;int&gt;
1      0     0     0       0       0       0     0     0     0     0      0
  guardian traveltime studytime failures schoolsup famsup paid.x activities
     &lt;int&gt;      &lt;int&gt;     &lt;int&gt;    &lt;int&gt;     &lt;int&gt;  &lt;int&gt;  &lt;int&gt;      &lt;int&gt;
1        0          0         0        0         0      0      0          0
  nursery higher internet romantic famrel freetime goout  Dalc  Walc health
    &lt;int&gt;  &lt;int&gt;    &lt;int&gt;    &lt;int&gt;  &lt;int&gt;    &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;  &lt;int&gt;
1       0      0        0        0      0        0     0     0     0      0
  absences.x  G1.x  G2.x  G3.x paid.y absences.y  G1.y  G2.y  G3.y
       &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;  &lt;int&gt;      &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
1          0     0     0     0      0          0     0     0     0</code></pre>
</div>
</div>
<p>Again, we find that there are no missing values in our data.</p>
<p>Next we do some EDA for our categorical variables. We start with a one-way contingency table using <code>school</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data_join2<span class="sc">$</span>school)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 GP  MS 
287  33 </code></pre>
</div>
</div>
<p>The number 287 in the “GP” row is the number of students who go to the Gabriel Pereira school. From the output we see that far more students are in the “GP” school than in the “MS” school (287 vs.&nbsp;33, respectively).</p>
<p>Now we do a two-way contingency table using <code>school</code> and <code>Medu</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data_join2<span class="sc">$</span>school, data_join2<span class="sc">$</span>Medu)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    
     Higher_Ed Secondary 5th_to_9th Primary None
  GP       114        66         78      27    2
  MS         9         8          6      10    0</code></pre>
</div>
</div>
<p>The number 114 at the intersection of the <code>GP</code> row and <code>Higher_Ed</code> column is the number of students at the “GP” school who had mothers who completed higher education. This number for the “GP” school is higher than for other education levels, suggesting that if a student goes to Gabriel Pereira, then the most likely education level of their mother is higher education.</p>
<p>Next we create a three-way contingency table using <code>school</code>, <code>Medu</code>, and <code>Mjob</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data_join2<span class="sc">$</span>school, data_join2<span class="sc">$</span>Medu, data_join2<span class="sc">$</span>Mjob)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>, ,  = at_home

    
     Higher_Ed Secondary 5th_to_9th Primary None
  GP         1         6         17      12    1
  MS         1         1          2       3    0

, ,  = health

    
     Higher_Ed Secondary 5th_to_9th Primary None
  GP        24         3          2       1    0
  MS         0         0          0       0    0

, ,  = other

    
     Higher_Ed Secondary 5th_to_9th Primary None
  GP        18        33         39      11    1
  MS         3         1          3       7    0

, ,  = services

    
     Higher_Ed Secondary 5th_to_9th Primary None
  GP        23        23         20       3    0
  MS         0         5          1       0    0

, ,  = teacher

    
     Higher_Ed Secondary 5th_to_9th Primary None
  GP        48         1          0       0    0
  MS         5         1          0       0    0</code></pre>
</div>
</div>
<p>We see from the output that we have a 2 by 5 by 5 array. The number at position [1,1,5] is the number of students at “GP” school whose mothers completed higher education and work as teachers. This number is 48. Examining the rest of the row containing this value, nearly all mothers of students at Gabriel Pereira who work as teachers completed higher education (specifically, all but one).</p>
<p>Now we create a conditional two-way table using <code>table()</code>. We will create a two way table of <code>school</code> and <code>Medu</code> conditioned on <code>Mjob</code>. Specifically, we will condition on mothers job being teacher. We do this conditioning using two methods.</p>
<p>For the first method.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>conditioned_tbl <span class="ot">&lt;-</span> data_join2 <span class="sc">|&gt;</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Mjob <span class="sc">==</span> <span class="st">'teacher'</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(conditioned_tbl[,<span class="fu">c</span>(<span class="st">'school'</span>, <span class="st">'Medu'</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Medu
school Higher_Ed Secondary 5th_to_9th Primary None
    GP        48         1          0       0    0
    MS         5         1          0       0    0</code></pre>
</div>
</div>
<p>For the second method.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(data_join2<span class="sc">$</span>school, data_join2<span class="sc">$</span>Medu, data_join2<span class="sc">$</span>Mjob)[ , ,<span class="st">'teacher'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    
     Higher_Ed Secondary 5th_to_9th Primary None
  GP        48         1          0       0    0
  MS         5         1          0       0    0</code></pre>
</div>
</div>
<p>We see both methods return the same conditional two-way table. This table shows us that regardless of the school a student attends, if their mother was a teacher, then their mother was likely to have completed higher education.</p>
<p>Now we use <code>dplyr</code> to create a two-way contingency table. We will create the same two-way table we created above. We use the <code>pivot_wider()</code> function from <code>tidyr</code> to make the result look more like the output from <code>table()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>data_join2 <span class="sc">|&gt;</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(school, Medu) <span class="sc">|&gt;</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> Medu, <span class="at">values_from =</span> count)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'school'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
# Groups:   school [2]
  school Higher_Ed Secondary `5th_to_9th` Primary  None
  &lt;fct&gt;      &lt;int&gt;     &lt;int&gt;        &lt;int&gt;   &lt;int&gt; &lt;int&gt;
1 GP           114        66           78      27     2
2 MS             9         8            6      10    NA</code></pre>
</div>
</div>
<p>We see that this is identical to the two-way table for <code>school</code> and <code>Medu</code> created above with the <code>table()</code> function, except that there is an <code>NA</code> where we want a zero. We can easily fix this with the <code>replace_na()</code> function from <code>tidyr</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>data_join2 <span class="sc">|&gt;</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(school, Medu) <span class="sc">|&gt;</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">count =</span> <span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> Medu, <span class="at">values_from =</span> count) <span class="sc">|&gt;</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">replace_na</span>(<span class="fu">list</span>(<span class="at">None =</span> <span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'school'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
# Groups:   school [2]
  school Higher_Ed Secondary `5th_to_9th` Primary  None
  &lt;fct&gt;      &lt;int&gt;     &lt;int&gt;        &lt;int&gt;   &lt;int&gt; &lt;int&gt;
1 GP           114        66           78      27     2
2 MS             9         8            6      10     0</code></pre>
</div>
</div>
<p>The final task we will do with categorical data is to create a stacked bar graph and side-by-side bar graph. We will do this with the variables <code>Medu</code> and <code>school</code>.</p>
<p>First we create the stacked bar graph.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>data_join2 <span class="sc">|&gt;</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Medu)) <span class="sc">+</span> <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">fill =</span> school)) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">'Mother</span><span class="sc">\'</span><span class="st">s Education Level'</span>, <span class="at">y =</span> <span class="st">'Counts'</span>, <span class="at">title =</span> <span class="st">'Distribution of Students</span><span class="sc">\'</span><span class="st"> Mother</span><span class="sc">\'</span><span class="st">s Level of Education by School'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Homework5_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Next we create the side-by-side bar graph. We can use the same code but add a position argument.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>data_join2 <span class="sc">|&gt;</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Medu)) <span class="sc">+</span> <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">fill =</span> school), <span class="at">position =</span> <span class="st">'dodge'</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">'Mother</span><span class="sc">\'</span><span class="st">s Education Level'</span>, <span class="at">y =</span> <span class="st">'Counts'</span>, <span class="at">title =</span> <span class="st">'Distribution of Students</span><span class="sc">\'</span><span class="st"> Mother</span><span class="sc">\'</span><span class="st">s Level of Education by School'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Homework5_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Viewing the plots, we gather a lot of the same information we discussed when creating contingency tables (the numerical summary for categorical data). We can see that the mothers of students at the Gabriel Pereira school have high rates of higher education. Whereas for students at the Mousinho da Silveira school, the distribution of education levels is relatively uniform.</p>
<p>Now it is time for some EDA on numeric variables. The numeric variables are age, absences, and the three test grade variables (G1, G2, and G3) from each data set (math and Portuguese). There are two each for G1, G2, G3, and absences, since there is a math value and a Portuguese value for each variable. There is only one age variable. This gives a total of 9 numeric variables in the <code>data_join2</code> data set.</p>
<p>First we find measures of center and spread for 3 of these variables. We will use <code>absences.x</code>, <code>absences.y</code>, and <code>G3.x</code>. We will use mean and median as our measures of center, and we will use standard deviation (sd) and interquartile range (IQR) as our measures of spread. We return the desired values in a tibble.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>data_join2 <span class="sc">|&gt;</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(absences.x, absences.y, G3.x) <span class="sc">|&gt;</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), </span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">.fns =</span> <span class="fu">list</span>(<span class="st">'mean'</span> <span class="ot">=</span> mean, <span class="st">'median'</span> <span class="ot">=</span> median, <span class="st">'sd'</span> <span class="ot">=</span> sd, <span class="st">'IQR'</span> <span class="ot">=</span> IQR),</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">.names =</span> <span class="st">'{.fn}_{.col}'</span>)) <span class="sc">|&gt;</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width =</span> <span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  mean_absences.x median_absences.x sd_absences.x IQR_absences.x mean_absences.y
            &lt;dbl&gt;             &lt;dbl&gt;         &lt;dbl&gt;          &lt;dbl&gt;           &lt;dbl&gt;
1            5.41                 4          7.84           7.25            3.25
  median_absences.y sd_absences.y IQR_absences.y mean_G3.x median_G3.x sd_G3.x
              &lt;dbl&gt;         &lt;dbl&gt;          &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;   &lt;dbl&gt;
1                 2          4.56              4      11.0          11    4.30
  IQR_G3.x
     &lt;dbl&gt;
1        5</code></pre>
</div>
</div>
<p>The output suggests that students may have fewer absences and less variability in absences in Portuguese class than in math class. We of course would need to conduct a statistical test to confirm.</p>
<p>We will subset the data to find measures of center and spread for only those students who had at least one absence.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>data_join2 <span class="sc">|&gt;</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(absences.x, absences.y, G3.x) <span class="sc">|&gt;</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(absences.x <span class="sc">&gt;</span> <span class="dv">0</span>,</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>         absences.y <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">|&gt;</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), </span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">.fns =</span> <span class="fu">list</span>(<span class="st">'mean'</span> <span class="ot">=</span> mean, <span class="st">'median'</span> <span class="ot">=</span> median, <span class="st">'sd'</span> <span class="ot">=</span> sd, <span class="st">'IQR'</span> <span class="ot">=</span> IQR),</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">.names =</span> <span class="st">'{.fn}_{.col}'</span>)) <span class="sc">|&gt;</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width =</span> <span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  mean_absences.x median_absences.x sd_absences.x IQR_absences.x mean_absences.y
            &lt;dbl&gt;             &lt;dbl&gt;         &lt;dbl&gt;          &lt;dbl&gt;           &lt;dbl&gt;
1            9.20                 6          9.75              8            5.91
  median_absences.y sd_absences.y IQR_absences.y mean_G3.x median_G3.x sd_G3.x
              &lt;dbl&gt;         &lt;dbl&gt;          &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;   &lt;dbl&gt;
1                 4          5.04           5.25      11.6          11    3.43
  IQR_G3.x
     &lt;dbl&gt;
1        5</code></pre>
</div>
</div>
<p>In this subset of students with at least one absence, we again see that students may have fewer absences and less variability in absences in Portuguese class than in math class. Like the un-subsetted case above, we would need a statistical test to confirm.</p>
<p>Next we find the same measures of center and spread for the same variables, but we do so across the grouping variable <code>school</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>data_join2 <span class="sc">|&gt;</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(school) <span class="sc">|&gt;</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(absences.x, absences.y, G3.x) <span class="sc">|&gt;</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), </span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">.fns =</span> <span class="fu">list</span>(<span class="st">'mean'</span> <span class="ot">=</span> mean, <span class="st">'median'</span> <span class="ot">=</span> median, <span class="st">'sd'</span> <span class="ot">=</span> sd, <span class="st">'IQR'</span> <span class="ot">=</span> IQR),</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">.names =</span> <span class="st">'{.fn}_{.col}'</span>)) <span class="sc">|&gt;</span></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width =</span> <span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Adding missing grouping variables: `school`</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 13
  school mean_absences.x median_absences.x sd_absences.x IQR_absences.x
  &lt;fct&gt;            &lt;dbl&gt;             &lt;dbl&gt;         &lt;dbl&gt;          &lt;dbl&gt;
1 GP                5.64                 4          8.10              8
2 MS                3.42                 2          4.55              4
  mean_absences.y median_absences.y sd_absences.y IQR_absences.y mean_G3.x
            &lt;dbl&gt;             &lt;dbl&gt;         &lt;dbl&gt;          &lt;dbl&gt;     &lt;dbl&gt;
1            3.34                 2          4.72              4     11.2 
2            2.39                 2          2.66              4      9.88
  median_G3.x sd_G3.x IQR_G3.x
        &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;
1          11    4.27        5
2          10    4.44        4</code></pre>
</div>
</div>
<p>The mean number of absences in math class appear higher for Gabriel Pereira students than Mousinho da Silveira students, and yet students in Gabriel Pereira have higher mean math scores (<code>G3.x</code>). Again, we need statistical tests to confirm these differences.</p>
<p>Now we find measures of center and spread for the same 3 variables across two grouping variables: <code>school</code> and <code>sex</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>data_join2 <span class="sc">|&gt;</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(school, sex) <span class="sc">|&gt;</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(absences.x, absences.y, G3.x) <span class="sc">|&gt;</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), </span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">.fns =</span> <span class="fu">list</span>(<span class="st">'mean'</span> <span class="ot">=</span> mean, <span class="st">'median'</span> <span class="ot">=</span> median, <span class="st">'sd'</span> <span class="ot">=</span> sd, <span class="st">'IQR'</span> <span class="ot">=</span> IQR),</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">.names =</span> <span class="st">'{.fn}_{.col}'</span>)) <span class="sc">|&gt;</span></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">width =</span> <span class="cn">Inf</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Adding missing grouping variables: `school`, `sex`
`summarise()` has grouped output by 'school'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 14
# Groups:   school [2]
  school sex    mean_absences.x median_absences.x sd_absences.x IQR_absences.x
  &lt;fct&gt;  &lt;fct&gt;            &lt;dbl&gt;             &lt;dbl&gt;         &lt;dbl&gt;          &lt;dbl&gt;
1 GP     Female            6.12               4            9.80           7   
2 GP     Male              5.10               4            5.55           6.75
3 MS     Female            3.33               0            5.04           4   
4 MS     Male              3.58               3.5          3.73           2.5 
  mean_absences.y median_absences.y sd_absences.y IQR_absences.y mean_G3.x
            &lt;dbl&gt;             &lt;dbl&gt;         &lt;dbl&gt;          &lt;dbl&gt;     &lt;dbl&gt;
1            3.61               2            5.18              6     10.5 
2            3.04               2            4.12              4     12.0 
3            2.48               1            2.94              4     10.0 
4            2.25               2.5          2.18              4      9.58
  median_G3.x sd_G3.x IQR_G3.x
        &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;
1          11    4.43      5  
2          12    3.96      5  
3          10    4.63      3  
4          10    4.27      4.5</code></pre>
</div>
</div>
<p>It appears from the output that female students at Gabriel Pereira may have lower math scores on average than male students, but that there is no difference in math scores between male and female students at Mousinho da Silveira. Again, we emphasize statistical tests are needed to assess the probability that the observed difference in mean/median test scores is do to sampling variability rather than true population differences.</p>
<p>Next we create a correlation matrix between all the numeric variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>data_join2 <span class="sc">|&gt;</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(age, G1.x, G2.x, G3.x, absences.x, G1.y, G2.y, G3.y, absences.y) <span class="sc">|&gt;</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    age        G1.x        G2.x        G3.x  absences.x
age         1.000000000 -0.11037935 -0.18618740 -0.20603186  0.14392517
G1.x       -0.110379348  1.00000000  0.86588796  0.81859418 -0.06946116
G2.x       -0.186187399  0.86588796  1.00000000  0.91357599 -0.07580245
G3.x       -0.206031862  0.81859418  0.91357599  1.00000000 -0.02811847
absences.x  0.143925170 -0.06946116 -0.07580245 -0.02811847  1.00000000
G1.y       -0.050549678  0.59293522  0.54300736  0.52288461 -0.09247761
G2.y        0.029366456  0.59517224  0.56521350  0.54545279 -0.14516402
G3.y       -0.009103257  0.54388734  0.49603265  0.47595650 -0.13572638
absences.y  0.047331821 -0.08760610 -0.12636236 -0.11664046  0.56381559
                  G1.y        G2.y         G3.y  absences.y
age        -0.05054968  0.02936646 -0.009103257  0.04733182
G1.x        0.59293522  0.59517224  0.543887345 -0.08760610
G2.x        0.54300736  0.56521350  0.496032649 -0.12636236
G3.x        0.52288461  0.54545279  0.475956497 -0.11664046
absences.x -0.09247761 -0.14516402 -0.135726385  0.56381559
G1.y        1.00000000  0.88415041  0.825414320 -0.09864117
G2.y        0.88415041  1.00000000  0.894309821 -0.12070727
G3.y        0.82541432  0.89430982  1.000000000 -0.07145201
absences.y -0.09864117 -0.12070727 -0.071452010  1.00000000</code></pre>
</div>
</div>
<p>Interesting fact…</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>